name: ITZAPPZ
favicon: null
layout_spectrum: 0.93416
typography_spectrum: 0.90227
title: ITZAPPZ = It's all about the apps!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76d2eb'
    - '#fafafa'
    - '#ffc337'
    - '#fc4c01'
    - '#007bff'
  brandStrength: 0.1875
  lightness: 0.3764025401324034
  saturation: 0.875
  rhythmicContrast: 0.24738261988386512
purpose: []
