name: ITZAPPZ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90227
title: ITZAPPZ = It's all about the apps!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76d2eb'
    - '#fafafa'
    - '#ffc337'
    - '#fc4c01'
    - '#007bff'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
