name: ITZAPPZ
favicon: null
layout_spectrum: 0.688976890174672
typography_spectrum: 0.20653538242913783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.3764025401324034
  saturation: 0.5288077236618847
  rhythmicContrast: 0.24738261988386512
purpose: []
